### PR TITLE
Gets the correct tarball url

### LINKED ISSUE #1: Fails with Hugo v0.20.3 and v0.20.4
I used the [master](https://github.com/netlify/binrc/tree/master) version with `go get` and it fails to download Hugo v0.20.3 and v0.20.4 the most recent version that works is v0.20.2

### Works

```bash
$ HUGO_VERSION=0.20.2 binrc install spf13/hugo
/Users/Abe/.binrc/binaries/spf13/hugo/v0.20.2/hugo
```

### Fails

```bash
$ HUGO_VERSION=0.20.3 binrc install spf13/hugo
error downloading project spf13/hugo, from https://github.com/spf13/hugo/releases/download/v0.20.3/hugo_0.20.3_Linux-64bit.tar.gz - binary doesn't seem to exist: 404
```

```bash
$ HUGO_VERSION=0.20.4 binrc install spf13/hugo
error renaming /Users/Abe/.binrc/binaries/spf13/hugo/v0.20.4/binrc-879126892/hugo_0.20.4_linux_amd64/hugo_0.20.4_linux_amd64 to /Users/Abe/.binrc/binaries/spf13/hugo/v0.20.4/hugo: rename /Users/Abe/.binrc/binaries/spf13/hugo/v0.20.4/binrc-879126892/hugo_0.20.4_linux_amd64/hugo_0.20.4_linux_amd64 /Users/Abe/.binrc/binaries/spf13/hugo/v0.20.4/hugo: no such file or directory
```

### PR DESCRIPTION
**Pull request by AbeEstrada**
Partially fixes #1 getting the correct tarball url using the GitHub API for the releases.

### CODE REVIEW

**Comment by calavera** [comment]
Thanks, I thought about that possibility. Unfortunately, GitHub has a rather aggressive policy for unauthenticated requests that I'd rather not reach.

A different approach would be to send a HEAD request to possible known urls and see if it's a valid one. We could also restrict that by version, although I'm not very fond of hardcoding versions, we could have a map like this:

```go
versions := map[string]string {
  ">=0.19, <0.20.3": "url template for that range",
  ">=0.20.3": "url template for that range",
}
```

**Comment by AbeEstrada** [comment]
For unauthenticated requests the limit is 60 requests per hour (https://developer.github.com/v3/#rate-limiting)

What about caching the releases per project every hour?

**Comment by AbeEstrada** [comment]
The GitHub API it is not called if the binary has already been downloaded

**Comment by calavera** [comment]
Thanks a lot. I think this is a more correct solution, but I'm going to go with #3 for now. I'm going to open a couple of issues with improvements to discuss how to move the project further.

**Pull request closed without merging**
